# https://taskfile.dev/
version: '3'

env:
  GOLANGCI_LINT_VERSION: 1.55.2

dotenv: ['.env']

tasks:

  tools:
    desc: 'checks if all tools used in this project are ready or in the correct version'
    cmds:
      - task: gofumpt
      - task: lint-check-version

  gofumpt:
    internal: true
    status:
      - which gofumpt
    cmds:
      - go install mvdan.cc/gofumpt@latest

  lint-check-version:
    internal: true
    status:
      - bin/golangci-lint --version | grep -q "{{.GOLANGCI_LINT_VERSION}}"
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{.TASKFILE_DIR}}/bin "v{{.GOLANGCI_LINT_VERSION}}"

  test:
    desc: 'runs Go tests'
    cmds:
      - go test ./... -v

  lint:
    desc: 'runs Go linter checks'
    deps: [lint-check-version]
    cmds:
      - bin/golangci-lint run --timeout 5m --color always --max-issues-per-linter 0 --max-same-issues 0

  format:
    desc: 'formats the code'
    deps: [gofumpt]
    cmds:
      - gofumpt -l -w .
